#ifndef APICALLSTATUS_H
#define APICALLSTATUS_H

/**
 * @brief Status codes for service API calls
 */
enum class ApiCallStatus
{
    SUCCESS,
    USERNAME_ALREADY_EXISTS,
    INVALID_USERNAME,
    INVALID_PASSWORD,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FILE_ALREADY_EXISTS,
    INVALID_PATH,
    INVALID_TRANSFER_ID,
    UNKNOWN_ERROR
};

#endif  // APICALLSTATUS_H
